language: node_js
node_js:
  - "node"
services:
  - mongodb
cache: yarn
before_script:
  - sleep 15
  - mongo canteen --eval 'db.createUser({user:"test",pwd:"test",roles:[{role:"readWrite",db:"canteen"}]});'
  - echo '{"mongo":"mongodb://test:test@localhost/canteen"}' > ./config.json
script:
  - yarn run test
